// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBC7e4jGt1V79QAaxrvl32zhruQnUsiTJg',
    appId: '1:519605037074:web:35dac25f3344d2dad5d0cb',
    messagingSenderId: '519605037074',
    projectId: 'flutterlogin-4ed1e',
    authDomain: 'flutterlogin-4ed1e.firebaseapp.com',
    storageBucket: 'flutterlogin-4ed1e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXBw3HyQ4kB2NLO9g4jP_ftBgXJDNTGfY',
    appId: '1:519605037074:android:fadc53c36fa1e883d5d0cb',
    messagingSenderId: '519605037074',
    projectId: 'flutterlogin-4ed1e',
    storageBucket: 'flutterlogin-4ed1e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmaV85mpA5K8neG4BjE0RIgsmW9wtuWJU',
    appId: '1:519605037074:ios:74d0ef908cd28801d5d0cb',
    messagingSenderId: '519605037074',
    projectId: 'flutterlogin-4ed1e',
    storageBucket: 'flutterlogin-4ed1e.appspot.com',
    iosClientId: '519605037074-q8r0hhbrchahh24seka97ue2iqho9ubo.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseLogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmaV85mpA5K8neG4BjE0RIgsmW9wtuWJU',
    appId: '1:519605037074:ios:991f4aef66d60060d5d0cb',
    messagingSenderId: '519605037074',
    projectId: 'flutterlogin-4ed1e',
    storageBucket: 'flutterlogin-4ed1e.appspot.com',
    iosClientId: '519605037074-sd4naracd9a36qn4ks9n87546hlutidp.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseLogin.RunnerTests',
  );
}
